--
-- PostgreSQL database dump
--

\restrict rYWbTSjbpAbC8f4OrfYfFx60PEBldfBpStaQHpwOWkLVwoQSnjLceBIEaNJlKWX

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: character; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public."character" (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    surname character varying(50) NOT NULL,
    caste character varying(20) DEFAULT NULL::character varying,
    knowledge character varying(20) DEFAULT NULL::character varying,
    intelligence smallint,
    strength smallint,
    image character varying(50) DEFAULT NULL::character varying,
    creation timestamp(0) without time zone NOT NULL,
    slug character varying(20) NOT NULL,
    kind character varying(20) NOT NULL,
    identifier character varying(40) NOT NULL
);


ALTER TABLE public."character" OWNER TO app;

--
-- Name: character_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public."character" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.character_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO app;

--
-- Data for Name: character; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public."character" (id, name, surname, caste, knowledge, intelligence, strength, image, creation, slug, kind, identifier) FROM stdin;
2	Anardil	Amie du soleil	Magicien	Sciences	180	180	/dames/anardil.webp	2026-03-30 14:07:49	anardil	Dame	0bc822e1a6ecf4c22c033b7ba8c793a0f31ab885
3	Anardil	Amie du soleil	Magicien	Sciences	180	180	/dames/anardil.webp	2026-03-30 14:15:09	anardil	Dame	ce216eabf01e339fbabc52d3a97de691f3899a40
4	Anardil	Amie du soleil	Magicien	Sciences	180	180	/dames/anardil.webp	2026-03-30 14:15:57	anardil	Dame	94b202311b0b4fbd0d4fcb0a8ca419d132d2ff92
5	Anardil	Amie du soleil	Magicien	Sciences	180	180	/dames/anardil.webp	2026-03-30 14:31:15	anardil	Dame	1e4c0d9bdbea3da91f13ff36af538df133da4be2
6	Anardil	Amie du soleil	Magicien	Sciences	180	180	/dames/anardil.webp	2026-03-30 14:32:26	anardil	Dame	a94f1eececd0f4822f57e7a081f1bcf6c6cec333
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260330124206	2026-03-30 13:23:34	4
DoctrineMigrations\\Version20260330140412	2026-03-30 14:04:22	6
\.


--
-- Name: character_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.character_id_seq', 6, true);


--
-- Name: character character_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public."character"
    ADD CONSTRAINT character_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- PostgreSQL database dump complete
--

\unrestrict rYWbTSjbpAbC8f4OrfYfFx60PEBldfBpStaQHpwOWkLVwoQSnjLceBIEaNJlKWX

