<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504121254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "building" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, caste VARCHAR(20) DEFAULT NULL, strength INT DEFAULT NULL, image VARCHAR(50) DEFAULT NULL, price INT DEFAULT NULL, stars SMALLINT DEFAULT NULL, identifier VARCHAR(40) NOT NULL, creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "building"');
    }
}
