<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260507133736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE "character" ADD utilisateur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB034FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_937AB034FB88E14F ON "character" (utilisateur_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE "character" DROP CONSTRAINT FK_937AB034FB88E14F');
        $this->addSql('DROP INDEX IDX_937AB034FB88E14F');
        $this->addSql('ALTER TABLE "character" DROP utilisateur_id');
    }
}
